"""Shared services exposed to independently maintained feature modules."""

from .events import EventBus
from .ghost_keys import (
    GHOST_MODES,
    GHOST_MODE_HOLD,
    GHOST_MODE_LABELS,
    GHOST_MODE_PULSE,
    GHOST_SCOPES,
    GHOST_SCOPE_CAR,
    GHOST_SCOPE_GLOBAL,
    GHOST_SCOPE_LABELS,
    MAX_GHOST_ROWS,
    MAX_GHOST_TRIGGERS,
    default_ghost_row,
    find_ghost_row,
    ghost_row_is_active,
    ghost_row_problem,
    ghost_row_title,
    merge_ghost_rows,
    next_ghost_row_id,
    normalize_ghost_mode,
    normalize_ghost_scope,
    normalize_ghost_triggers,
    sanitize_ghost_row,
    sanitize_ghost_rows,
    split_ghost_rows_by_scope,
)
from .iracing_controls_file import (
    CONTROLS_CFG_INPUT_TYPE_AXIS,
    CONTROLS_CFG_INPUT_TYPE_JOYSTICK,
    CONTROLS_CFG_INPUT_TYPE_KEYBOARD,
    CONTROLS_CFG_INPUT_TYPE_UNBOUND,
    ControlRecord,
    catalog_by_name,
    parse_controls_catalog,
)
from .second_throttle import SecondThrottleEngine, SecondThrottleSnapshot
from .second_throttle_macros import (
    MAX_SECOND_THROTTLE_MACROS,
    SECOND_THROTTLE_PIT_MACRO_ID,
    SecondThrottleAutomation,
    SecondThrottleAutomationEvent,
    SecondThrottlePedalEvent,
    SecondThrottlePedalTakeover,
    default_second_throttle_macro,
    default_second_throttle_pit_macro,
    lapdist_in_range,
    macro_lapdist_range,
    normalize_pedal_takeover_threshold,
    parse_lapdist_pct,
    sanitize_second_throttle_macro,
    sanitize_second_throttle_macros,
    sanitize_second_throttle_pit_macro,
)
from .telemetry import TelemetryHub, TelemetryProxy, TelemetryStatus

CORE_API_VERSION = "1.0"

__all__ = [
    "CONTROLS_CFG_INPUT_TYPE_AXIS",
    "CONTROLS_CFG_INPUT_TYPE_JOYSTICK",
    "CONTROLS_CFG_INPUT_TYPE_KEYBOARD",
    "CONTROLS_CFG_INPUT_TYPE_UNBOUND",
    "CORE_API_VERSION",
    "ControlRecord",
    "EventBus",
    "GHOST_MODES",
    "GHOST_MODE_HOLD",
    "GHOST_MODE_LABELS",
    "GHOST_MODE_PULSE",
    "GHOST_SCOPES",
    "GHOST_SCOPE_CAR",
    "GHOST_SCOPE_GLOBAL",
    "GHOST_SCOPE_LABELS",
    "MAX_GHOST_ROWS",
    "MAX_GHOST_TRIGGERS",
    "MAX_SECOND_THROTTLE_MACROS",
    "SECOND_THROTTLE_PIT_MACRO_ID",
    "catalog_by_name",
    "default_ghost_row",
    "find_ghost_row",
    "ghost_row_is_active",
    "ghost_row_problem",
    "ghost_row_title",
    "merge_ghost_rows",
    "next_ghost_row_id",
    "normalize_ghost_mode",
    "normalize_ghost_scope",
    "normalize_ghost_triggers",
    "parse_controls_catalog",
    "sanitize_ghost_row",
    "sanitize_ghost_rows",
    "split_ghost_rows_by_scope",
    "SecondThrottleAutomation",
    "SecondThrottleAutomationEvent",
    "SecondThrottlePedalEvent",
    "SecondThrottlePedalTakeover",
    "SecondThrottleEngine",
    "SecondThrottleSnapshot",
    "TelemetryHub",
    "TelemetryProxy",
    "TelemetryStatus",
    "default_second_throttle_macro",
    "default_second_throttle_pit_macro",
    "lapdist_in_range",
    "macro_lapdist_range",
    "normalize_pedal_takeover_threshold",
    "parse_lapdist_pct",
    "sanitize_second_throttle_macro",
    "sanitize_second_throttle_macros",
    "sanitize_second_throttle_pit_macro",
]
